#!/bin/bash
#PBS -P DementiaCFDNA
#PBS -N bcl2fastq
#PBS -l select=1:ncpus=4:mem=96GB
#PBS -l walltime=12:00:00
#PBS -M zacchatt@gmail.com

module load bcl2fastq2
# run using bcl2fastq v2.19.0.316 software

runfolder_dir=/project/RDS-FMH-FFEPIGENETICS-RW/scwgbs/201021_NS500799_0624_AHJCNNAFX2
input_dir=${runfolder_dir}/Data/Intensities/BaseCalls

cd $runfolder_dir

bcl2fastq \
-i $input_dir \
--create-fastq-for-index-reads \
--with-failed-reads \
--use-bases-mask Y*,I10,I20,Y*
