#!/bin/bash
#PBS -P DementiaCFDNA
#PBS -N demultiplex_trim_scimet
#PBS -l select=1:ncpus=32:mem=60GB
#PBS -l walltime=20:00:00
#PBS -M plam7692@uni.sydney.edu.au

## load modules
module load trimgalore
module load perl
module load python/3.8.2
module load fastqc

## set directories
data_dir=/project/RDS-FMH-DementiaCFDNA-RW/Epigenetics/scimet
cd ${data_dir}
code_dir=/project/RDS-FMH-DementiaCFDNA-RW/local_lib/code/scimet_scripts

## set variables
SAMPLE_NAME=Undetermined.merged

bash ${code_dir}/demultiplex_trim_scimet.sh $SAMPLE_NAME $data_dir $code_dir
