#!/bin/bash
#PBS -P DementiaCFDNA
#PBS -N demultiplex_trim_scimet
#PBS -l select=1:ncpus=32:mem=60GB
#PBS -l walltime=10:00:00
#PBS -M plam7692@uni.sydney.edu.au

# load modules
module load trimgalore
module load perl
module load python/3.8.2
module load fastqc

# set directories and variables
data_dir=/project/RDS-FMH-DementiaCFDNA-RW/Epigenetics/scimet/fastq
code_dir=/project/RDS-FMH-DementiaCFDNA-RW/local_lib/git_repo/scimet_scripts

cd ${data_dir}

SAMPLE_NAME=emmg
bash ${code_dir}/bash/demultiplex_trim_scimet.sh $SAMPLE_NAME $data_dir $code_dir $barcodes_scimet

SAMPLE_NAME=emn9
bash ${code_dir}/bash/demultiplex_trim_scimet.sh $SAMPLE_NAME $data_dir $code_dir $barcodes_scimet

SAMPLE_NAME=mg
bash ${code_dir}/bash/demultiplex_trim_scimet.sh $SAMPLE_NAME $data_dir $code_dir $barcodes_scimet

SAMPLE_NAME=n9
bash ${code_dir}/bash/demultiplex_trim_scimet.sh $SAMPLE_NAME $data_dir $code_dir $barcodes_scimet
